const SITE={name:'Sample Restaurant v0.04',slug:'sample-restaurant-v004-afo',version:'0.04',description:'Restaurant v0.04 turns a menu registry into item pages, markdown endpoints, schema, sitemap entries, and behind-the-dish stories.',preview:'https://sample-restaurant-v004-afo.jaredtechfit.workers.dev/',phone:'(949) 555-0404',cuisine:'California Coastal'};
const FIXED_DESSERT='https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1000&q=80';
const ITEMS=[['101','starters','seared-scallops','Seared Scallops','Golden scallops, charred lemon butter, sweet pea puree, crispy shallot.','22.00','https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=1000&q=80'],['102','starters','avocado-citrus-crudo','Avocado Citrus Crudo','Avocado, cara cara orange, basil oil, smoked salt, shaved fennel.','17.00','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1000&q=80'],['201','mains','pacific-halibut','Pacific Halibut','Charred corn, salsa verde, fingerling potatoes, herbs, olive oil.','36.00','https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1000&q=80'],['202','mains','wild-mushroom-campanelle','Wild Mushroom Campanelle','Brown butter, sage, parmesan, garden herbs, toasted breadcrumbs.','27.00','https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1000&q=80'],['301','desserts','meyer-lemon-posset','Meyer Lemon Posset','Silky lemon cream, berries, shortbread crumble, sea salt.','12.00',FIXED_DESSERT],['302','desserts','chocolate-sea-salt-tart','Chocolate Sea Salt Tart','Dark chocolate, caramel, cocoa nib, vanilla cream, flaky salt.','14.00',FIXED_DESSERT]];
const SECTIONS=[['starters','Starters','Bright coastal openers built for sharing.'],['mains','Mains','Seasonal center-plate dishes with California produce.'],['desserts','Desserts','Sunny sweets with citrus, chocolate, and texture.']];
const ARTICLES=[{slug:'behind-the-seared-scallops',item:'101',title:'Behind the Dish: Seared Scallops',body:'How one coastal starter becomes a structured content asset.'},{slug:'meyer-lemon-season',item:'301',title:'Meyer Lemon Season',body:'A short story that turns dessert into search and AI discovery content.'}];
const item=o=>({id:o[0],section:o[1],slug:o[2],name:o[3],description:o[4],price:o[5],image:o[6],diet:['VegetarianDiet'],story:`Behind the dish: ${o[3]} is generated from registry data.`});
const DATA=ITEMS.map(item),byId=Object.fromEntries(DATA.map(i=>[i.id,i])),byPath=Object.fromEntries(DATA.map(i=>[`/menu/${i.section}/${i.slug}`,i]));
export default{async fetch(req){const u=new URL(req.url),p=u.pathname;if(p==='/'||p==='/menu')return html(menu());if(p==='/menu.md')return txt(menuMd(),'text/markdown');if(p==='/registry.json')return json({sections:SECTIONS.map(([id,name,description])=>({id,name,description})),items:DATA,articles:ARTICLES});if(p==='/schema.json')return json(schema());if(p==='/health')return json({ok:true,worker:SITE.slug,version:SITE.version,preview_only:true,production_routes:[],custom_domains:[],bindings:[]});if(p==='/llms.txt')return txt(llms(),'text/plain');if(p==='/robots.txt')return txt(`User-agent: *\nAllow: /\nSitemap: ${SITE.preview}sitemap.xml\n`,'text/plain');if(p==='/sitemap.xml')return txt(sitemap(),'application/xml');if(p.startsWith('/items/')){const it=byId[p.split('/')[2]];return it?html(itemPage(it)):nf()}if(p.endsWith('.md')){const it=byPath[p.replace(/\.md$/,'')];return it?txt(itemMd(it),'text/markdown'):nf()}if(byPath[p])return html(itemPage(byPath[p]));if(p.startsWith('/articles/')){const a=ARTICLES.find(x=>x.slug===p.split('/')[2]?.replace(/\.md$/,''));return a?p.endsWith('.md')?txt(`# ${a.title}\n\n${a.body}\n`,'text/markdown'):html(page(a.title,`<article class="panel"><h1>${e(a.title)}</h1><p>${e(a.body)}</p></article>`)):nf()}return nf()}};
function menu(){return page('Menu content engine',`<section class="hero"><p class="eyebrow">Restaurant v0.04 · content engine</p><h1>One menu registry. Many pages.</h1><p>${e(SITE.description)}</p></section>${SECTIONS.map(([id,name,desc])=>`<section id="${id}"><p class="eyebrow">${name}</p><h2>${desc}</h2><div class="grid">${DATA.filter(i=>i.section===id).map(card).join('')}</div></section>`).join('')}`)}
function card(i){return `<article class="card"><img loading="lazy" decoding="async" src="${e(i.image)}" alt="${e(i.name)} plated dish"><div><span>${e(i.section)}</span><h3><a href="/menu/${e(i.section)}/${e(i.slug)}">${e(i.name)}</a></h3><p>${e(i.description)}</p><b>$${e(i.price)}</b><p><a href="/items/${e(i.id)}">/items/${e(i.id)}</a> · <a href="/menu/${e(i.section)}/${e(i.slug)}.md">Markdown</a></p></div></article>`}
function itemPage(i){return page(i.name,`<section class="item"><img src="${e(i.image)}" alt="${e(i.name)} plated dish"><div><p class="eyebrow">${e(i.section)} · item ${e(i.id)}</p><h1>${e(i.name)}</h1><p>${e(i.description)}</p><p class="price">$${e(i.price)}</p><p>${e(i.story)}</p></div><script type="application/ld+json">${JSON.stringify(itemSchema(i)).replace(/</g,'\\u003c')}</script></section>`)}
function schema(){return {'@context':'https://schema.org','@type':'Restaurant',name:SITE.name,url:SITE.preview,telephone:SITE.phone,servesCuisine:SITE.cuisine,hasMenu:{'@type':'Menu',hasMenuSection':SECTIONS.map(([id,name,description])=>({'@type':'MenuSection',name,description,hasMenuItem:DATA.filter(i=>i.section===id).map(itemSchema)}))}}}
function itemSchema(i){return {'@context':'https://schema.org','@type':'MenuItem',name:i.name,description:i.description,image:i.image,offers:{'@type':'Offer',price:i.price,priceCurrency:'USD',availability:'https://schema.org/InStock'}}}
function sitemap(){const urls=['/','/menu','/menu.md','/registry.json','/health','/llms.txt','/robots.txt','/sitemap.xml','/schema.json',...DATA.flatMap(i=>[`/items/${i.id}`,`/menu/${i.section}/${i.slug}`,`/menu/${i.section}/${i.slug}.md`]),...ARTICLES.map(a=>`/articles/${a.slug}`)];return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(x=>`<url><loc>${SITE.preview.replace(/\/$/,'')}${x}</loc></url>`).join('')}</urlset>`}
function menuMd(){return `# ${SITE.name} Menu\n\n${SECTIONS.map(([id,name])=>`## ${name}\n${DATA.filter(i=>i.section===id).map(i=>`- ${i.name} — $${i.price}. ${i.description}`).join('\n')}`).join('\n\n')}`}
function itemMd(i){return `# ${i.name}\n\n${i.description}\n\nPrice: $${i.price}\n\n${i.story}\n`}
function llms(){return `# ${SITE.name}\n\n${SITE.description}\n\nMeyer Lemon Posset image URL fixed. Preview-only.\n`}
function page(title,body){return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} | ${e(SITE.name)}</title><style>body{margin:0;background:#fff8ee;color:#14110d;font-family:Inter,system-ui,sans-serif}.shell{width:min(1160px,calc(100% - 32px));margin:auto}.top{position:sticky;top:0;background:#fff8eee6;border-bottom:1px solid #ddd;padding:16px}.brand{font-weight:900;color:inherit;text-decoration:none}.hero{padding:70px 0}.eyebrow{text-transform:uppercase;letter-spacing:.16em;color:#b76532;font-weight:900}h1{font-size:clamp(3rem,7vw,6rem);line-height:.9;letter-spacing:-.07em}h2{font-size:clamp(2rem,4vw,3.3rem);line-height:1}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card,.panel{border:1px solid #ddd;border-radius:28px;background:#fff;overflow:hidden;box-shadow:0 20px 60px #301e0e18}.card img{width:100%;height:190px;object-fit:cover;background:#f3eadc}.card div,.panel{padding:18px}.item{display:grid;grid-template-columns:1fr 1fr;gap:28px;padding:50px 0}.item img{width:100%;border-radius:30px}.price{font-size:1.5rem;color:#b76532;font-weight:900}@media(max-width:850px){.grid,.item{grid-template-columns:1fr}}</style></head><body><header class="top"><div class="shell"><a class="brand" href="/menu">${e(SITE.name)}</a></div></header><main class="shell">${body}</main><footer class="shell">v0.04 preview-only</footer></body></html>`}
function html(b){return new Response(b,{headers:{'content-type':'text/html; charset=utf-8','x-afo-preview-only':'true'}})}function txt(b,t){return new Response(b,{headers:{'content-type':`${t}; charset=utf-8`,'x-afo-preview-only':'true'}})}function json(b){return new Response(JSON.stringify(b,null,2),{headers:{'content-type':'application/json; charset=utf-8','x-afo-preview-only':'true'}})}function nf(){return new Response('Not found',{status:404})}function e(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
